### ISSUE TITLE
request add `CentOS 8` fast-vm-public-image

### ISSUE THREAD

**Issue by chhanz** [OndrejHome/fast-vm-public-images#10]
hello, @OndrejHome 

at last [`CentOS 8` release](https://twitter.com/CentOSProject/status/1173652996305170432).

i made fast-vm `centos 8` image. and i am used your rhel8 hack file, ks.

# Test log
## change file
```diff
[root@test-vm-host centos-8.0]# diff centos-8.ks rhel-8.ks 
35,37c35,37
< volgroup c8vg --pesize=4096 pv.1
< logvol swap  --fstype="swap" --size=256 --name=swap_lv --vgname=c8vg
< logvol /  --fstype="xfs" --size=5000 --name=root_lv --vgname=c8vg
---
> volgroup r8vg --pesize=4096 pv.1
> logvol swap  --fstype="swap" --size=256 --name=swap_lv --vgname=r8vg
> logvol /  --fstype="xfs" --size=5000 --name=root_lv --vgname=r8vg

[root@test-vm-host centos-8.0]# diff virt-install-centos-8.sh virt-install-rhel-8.sh 
9c9 
< --name centos-8-fastvm-install \
---
> --name rhel-8-fastvm-install \
21c21
< virsh --connect qemu:///system undefine centos-8-fastvm-install
---
> virsh --connect qemu:///system undefine rhel-8-fastvm-install

[root@test-vm-host centos-8.0]# diff 6g_centos-8-hacks.sh 6g_rhel-8-hacks.sh
28c28 
< guestfish -a "/dev/$THINPOOL_VG/$VM_NAME" -m /dev/r8vg/root_lv -m /dev/sda1:/boot --selinux <<EOF
---
> guestfish -a "/dev/$THINPOOL_VG/$VM_NAME" -m /dev/c8vg/root_lv -m /dev/sda1:/boot --selinux <<EOF
[root@test-vm-host centos-8.0]#
```

also `centos 8` need install  `libguestfs custom appliance`.
i follow your [requirement guide]( https://github.com/OndrejHome/fast-vm-public-images/tree/master/rhel).

finally, complate test!

```bash
[root@test-vm-host fast-vm]# fast-vm console 77 
도메인 fastvm-centos-8.0-77에 연결되었습니다 
Escape character is ^]

...

CentOS Linux 8 (Core) 
Kernel 4.18.0-80.el8.x86_64 on an x86_64

fastvm-centos-8-0-77 login: root 
Password:  
Last login: Wed Sep 25 15:42:04 on ttyS0 
[root@fastvm-centos-8-0-77 ~]# cat /etc/redhat-release  
CentOS Linux release 8.0.1905 (Core)  
[root@fastvm-centos-8-0-77 ~]# uname -a 
Linux fastvm-centos-8-0-77 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
[root@fastvm-centos-8-0-77 ~]#
```

please check my test log.
and request new `CentOS 8` image. 👍

**Comment by OndrejHome** [comment]
Hi @chhanz, files for CentOS 8.0 are now added to repository -both BIOS and UEFI versions. Mostly identical to RHEL 8.0 files ;)
I will update webpage with public images tomorrow once the images are synced on my mirror.

**Comment by OndrejHome** [comment]
Images (BIOS and UEFI) are now available for download from mirror. Links were added to web page listing commands for importing images. Thank you for reminding me about CentOS 8 !
I will close this issue now, if there are any other questions or comment, feel free to re-open it ;)

https://www.famera.cz/blog/fast-vm/image_list.html#centos_8_generated

**Comment by chhanz** [comment]
Thank you @OndrejHome . 🥇
